# Generated by Django 5.0.7 on 2025-02-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content_quality',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very Poor')], default=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='design_quality',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very Poor')], default=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_experience',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very Poor')], default=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(),
        ),
    ]
